part of 'lib/theme/theme.dart';

/// Generated by Forui CLI.
///
/// Color tokens and theme extensions for the generated theme.
final FColors lightColors = FColors(
  brightness: .light,
  systemOverlayStyle: .dark,
  barrier: Color(0x33000000),
  background: Color(0xFFFFFFFF),
  foreground: Color(0xFF0C0C09),
  primary: Color(0xFF008236),
  primaryForeground: Color(0xFFF0FDF4),
  secondary: Color(0xFFF4F4F0),
  secondaryForeground: Color(0xFF1D1D16),
  muted: Color(0xFFF4F4F0),
  mutedForeground: Color(0xFF7C7C67),
  destructive: Color(0xFFE7000B),
  destructiveForeground: Color(0xFFFAFAFA),
  error: Color(0xFFE7000B),
  errorForeground: Color(0xFFFAFAFA),
  card: Color(0xFFFFFFFF),
  border: Color(0xFFE8E8E3),
  extensions: const [AppColors()],
);

final FColors darkColors = FColors(
  brightness: .dark,
  systemOverlayStyle: .light,
  barrier: Color(0x7A000000),
  background: Color(0xFF0C0C09),
  foreground: Color(0xFFFBFBF9),
  primary: Color(0xFF016630),
  primaryForeground: Color(0xFFF0FDF4),
  secondary: Color(0xFF2B2B22),
  secondaryForeground: Color(0xFFFBFBF9),
  muted: Color(0xFF2B2B22),
  mutedForeground: Color(0xFFABAB9C),
  destructive: Color(0xFFFF6467),
  destructiveForeground: Color(0xFFFAFAFA),
  error: Color(0xFFFF6467),
  errorForeground: Color(0xFFFAFAFA),
  card: Color(0xFF1D1D16),
  border: Color(0x1AFFFFFF),
  extensions: const [AppColors()],
);

/// Provides convenient access to theme extensions on [FColors].
///
/// ```dart
/// final accent = context.theme.colors.app.accent; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final accent = context.theme.colors.accent; ✅
///
/// final accent = context.theme.colors.extension<AppColors>().accent; ❌
/// ```
extension FColorsExtensions on FColors {
  AppColors get app => extension<AppColors>();
}

/// Custom color tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.
class AppColors extends ThemeExtension<AppColors> {
  // TODO: add your color fields here:
  // final Color accent;

  const AppColors();

  @override
  AppColors copyWith() => const AppColors();

  @override
  AppColors lerp(covariant AppColors? other, double t) {
    if (other == null) {
      return this;
    }
    return const AppColors();
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppColors && runtimeType == other.runtimeType;

  @override
  int get hashCode => runtimeType.hashCode;
}
