import 'package:forui/forui.dart';
import 'package:flutter/material.dart';

part 'colors.dart';
part 'typography.dart';
part 'style.dart';
part 'icons.dart';

/// Generated by Forui CLI.
///
/// Regenerate using "dart forui theme create --preset egbbbc".
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart run forui style create [styles]
/// ```
///
/// See:
/// * https://forui.dev/docs/guides/customizing-themes for customizing themes.
/// * https://forui.dev/docs/guides/customizing-widget-styles for customizing individual widget styles.
FThemeData get lightTheme {
  // Change this to false to use the desktop variant of this theme.
  const touch = true;

  final colors = lightColors;

  final typography = _typography(colors: colors, touch: touch);

  final icons = _icons();

  final style = _style(colors: colors, typography: typography, touch: touch);

  final fields = FTextFieldSizeStyles(
    FTextFieldSizeStyles.inherit(
      colors: colors,
      typography: typography,
      style: style,
      touch: touch,
    ).apply([.all(const .delta(constraints: BoxConstraints(minHeight: 48)))]),
  );
  final labels = FLabelStyles.inherit(style: style);
  final leadingChoiceLabel = labels.horizontalLeadingStyle.copyWith(
    childPadding: const .value(
      EdgeInsets.symmetric(horizontal: 12, vertical: 14),
    ),
  );
  final trailingChoiceLabel = labels.horizontalTrailingStyle.copyWith(
    childPadding: const .value(
      EdgeInsets.symmetric(horizontal: 8, vertical: 14),
    ),
  );

  return FThemeData(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    touch: touch,
    textFieldStyles: fields,
    radioStyle: FRadioStyle.inherit(colors: colors, style: style, touch: touch)
        .copyWith(
          leadingLabelStyle: leadingChoiceLabel,
          trailingLabelStyle: trailingChoiceLabel,
        ),
    switchStyle: FSwitchStyle.inherit(colors: colors, style: style).copyWith(
      leadingLabelStyle: labels.horizontalLeadingStyle.copyWith(
        childPadding: const .value(
          EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        ),
      ),
      trailingLabelStyle: labels.horizontalTrailingStyle.copyWith(
        childPadding: const .value(
          EdgeInsets.symmetric(horizontal: 8, vertical: 8),
        ),
      ),
    ),
    buttonStyles:
        FButtonStyles.inherit(
          colors: colors,
          typography: typography,
          style: style,
          touch: touch,
        ).apply([
          .all(
            .delta([
              .all(
                const .delta(
                  contentStyle: .delta(
                    constraints: BoxConstraints(minWidth: 48, minHeight: 48),
                  ),
                  iconContentStyle: .delta(
                    constraints: BoxConstraints(minWidth: 48, minHeight: 48),
                  ),
                ),
              ),
            ]),
          ),
        ]),
    selectStyle: FSelectStyle.inherit(
      colors: colors,
      icons: icons,
      typography: typography,
      style: style,
      touch: touch,
    ).copyWith(fieldStyles: fields),
  );
}

FThemeData get darkTheme {
  // Change this to false to use the desktop variant of this theme.
  const touch = true;

  final colors = darkColors;

  final typography = _typography(colors: colors, touch: touch);

  final icons = _icons();

  final style = _style(colors: colors, typography: typography, touch: touch);

  return FThemeData(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    touch: touch,
  );
}
